version: "3.9"

services:
  backend:
    build: ./backend
    container_name: lab02-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: lab02-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
