name: Deploy to HuggingFace Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Upload to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}   # ✅ use GitHub secret
        run: |
          python - <<'EOF'
          import os
          from huggingface_hub import HfApi

          repo_id = "Jurk06/ML-React-APP"   # 👈 your HuggingFace Space repo
          token = os.environ["HF_TOKEN"]    # ✅ correctly read env var

          api = HfApi()
          api.upload_folder(
              folder_path=".",    # you can change to "./frontend" if only frontend
              repo_id=repo_id,
              repo_type="space",
              token=token
          )
          print("✅ Successfully pushed to HuggingFace Space:", repo_id)
          EOF
